---
- hosts: intrawiki2
  remote_user: "{{ansible_ssh_user}}"
  pre_tasks:
    - name: epel
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    - setup: 
  roles:
    - role: common-root
    - role: parsoid
      when: wysiwyg
    - role: wiki-root-common
    - role: intrawiki-root

        
