- yum: name=libselinux-python
- selinux: state=disabled
  ignore_errors: True    
- include: templates/authorize_me.yml 
- yum: name=epel-release
- name: base packages
  yum: name={{item}}
  with_items:
    - make
    - gcc
    - gettext
    - htop
    - ack
    - mc
    - ncdu
    - tmux
    - strace
    - psmisc
    - curl
    - git
    - wget
    - lynx
- lineinfile:
    dest: /etc/sudoers
    line: 'Defaults requiretty'
    state: absent
- lineinfile:
    dest: /etc/sudoers
    line: 'Defaults !requiretty'
    state: present



        
